// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://alibi.day
// Generated: 2026-05-29T01:00:15.992Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#162044' | '#bf7dad' | '#43849d' | '#ffffff' | '#3253c7' | '#081692' | '#0e3b56' | '#85346b' | '#4a60c6';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Figtree' | 'JetBrains Mono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '900' | '600';

export type SpacingToken = '2px' | '40px' | '64px' | '80px' | '123px' | '128px' | '449px';

export type RadiusToken = '16px';

export type DurationToken = '150ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
