// Framer Motion presets — generated by designlang (motionlang)
// Source: https://alibi.day
// 2026-05-29T01:00:15.993Z
//
//   import { transitions, variants } from './alibi.day-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  custom1: [0.4, 0, 0.2, 1], // 8× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.15,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.15, ease: easings.custom1 },
  fast:  { duration: 0.100, ease: easings.custom1 },
  slow:  { duration: 0.270, ease: easings.custom1 },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.040 } },
  },
};

export default { easings, durations, transitions, variants };
